### ISSUE TITLE
Sprint#1 - Product Backlog & Sprint Backlog  (Data da Entrega: 16/03)

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [LeonhardDuarth13/YAD188-G10-Telemedicina#2]
# Orientação para Entrega

O Grupo deve entregar nesta Issue ****somente**** Product Backlog & Sprint Backlog - no modelo enviado pela **_Profa. Ana Cláudia_** passou para vocês.

======

**Comment by LeonhardDuarth13** [comment]
[Product_Back_Log__Sprint_1.xlsx](https://github.com/LeonhardDuarth13/YAD188-G10-Telemedicina/files/8265650/Product_Back_Log__Sprint_1.xlsx)
