### ISSUE TITLE
Sprint#1 - Vídeo (gravação do Login + CRUD)  (Data da Entrega: 16/03)

### ISSUE THREAD

**Issue by ProfVerissimoFatec** [LeonhardDuarth13/YAD188-G10-Telemedicina#3]
# Orientação para Entrega

O Grupo deve entregar nesta Issue ****somente****  o vídeo produzido, e que será apresentado em aula

**Comment by LeonhardDuarth13** [comment]
https://user-images.githubusercontent.com/61330383/158639455-30c4c9c9-f333-4073-a63d-4bed3e4e2a2d.mp4
[apresentacao_telemedicina.pptx](https://github.com/LeonhardDuarth13/YAD188-G10-Telemedicina/files/8265680/apresentacao_telemedicina.pptx)
